### ISSUE TITLE
No real output to commands

### ISSUE THREAD

**Issue by phodina** [steadfasterX/lglaf#14]
Hi,
I've put the K40 into the updater mode and ran the tool
```
$ python3 lglaf.py
LGLAF.py by steadfasterX + Peter Wu (https://lekensteyn.nl/lglaf)
Type a shell command to execute or "exit" to leave.
# pwd
Hello, I am LAF. Nice to meet you.# uname -a
Hello, I am LAF. Nice to meet you.#
```

However, I'm unable to get any meaningful output.

Any idea what could be wrong?

**Comment by steadfasterX** [comment]
normal behavior for newer LAF versions and nothing (known) we can do about. 
LG had restricted the LAF protocol with every release up to the point where you cannot execute any commands in that shell.
