### ISSUE TITLE
Trying to run auth.py results in TypeError

### ISSUE THREAD

**Issue by GijsTimmers** [steadfasterX/lglaf#7]
Trying to run `auth.py` on a LG K10 2017 (M250N):

```
$ python auth.py 
Traceback (most recent call last):
  File "auth.py", line 73, in <module>
    main()
  File "auth.py", line 64, in main
    comm = lglaf.autodetect_device()
TypeError: autodetect_device() missing 1 required positional argument: 'cr'
```

**Comment by steadfasterX** [comment]
there is no need to run auth.py as lglaf will autodetect if its needed or not.
ensure you use g4-develop branch btw.

**Comment by GijsTimmers** [comment]
Thank you; I got a little bit further (see https://github.com/Lekensteyn/lglaf/issues/56#issuecomment-422426100)
